name: crawling
dependencies:
  - python==3.7.0
  - jupyter
  #- scipy==1.1.0
  #- pandas==0.23.4
  #- numpy==1.15.1
  - click
  - spyder-kernels
  - pip:
    - langdetect # deteccion de idiomas
    - beautifulsoup4 # para el text parser

# and then...
#conda install -n keywords -c conda-forge textacy==0.8.0
